import React from "react";
import "./App.css";

const HomePage = ({ onGetStarted }) => (
  <div className="homepage-container">
    {/* Header */}
    <header className="header">
      <div className="logo">IoT DataChain</div>
      <nav className="nav">
        <a href="#">Home</a>
        <a href="#">Register Device</a>
        <a href="#">Publish Data</a>
        <a href="#">Marketplace</a>
        <button className="connect-btn" onClick={onGetStarted}>Connect Wallet</button>
      </nav>
    </header>

    {/* Hero Section */}
    <section className="hero">
      <div className="hero-content">
        <h1>Buy, Sell, and Secure IoT Data on the Blockchain</h1>
        <p>
          Use this decentralized marketplace to transparently and securely trade data to/from IoT devices.
        </p>
        <button className="cta-btn" onClick={onGetStarted}>Get Started</button>
      </div>
      <div className="hero-image">
        {/* Remplace par une image ou illustration de ton choix */}
        <img src="https://cdn-icons-png.flaticon.com/512/4144/4144406.png" alt="IoT Blockchain" style={{width: "220px"}} />
      </div>
    </section>

    {/* About Section */}
    <section className="about">
      <h2>About</h2>
      <p>
        IoT DataChain is a decentralized marketplace designed to facilitate the secure and transparent trading of data generated by IoT devices.
        Our platform leverages blockchain technology to ensure trust and security.
      </p>
      <p>
        Technologies: Ethereum, Web3.js, Cloud, IoT.
      </p>
    </section>

    {/* Features Section */}
    <section className="features">
      <div className="feature-card">
        <span role="img" aria-label="IoT">📡</span>
        <h3>IoT Device Registration</h3>
        <p>Register and manage your IoT devices on the platform.</p>
      </div>
      <div className="feature-card">
        <span role="img" aria-label="Publish">📤</span>
        <h3>Publish Data</h3>
        <p>Publish your IoT device data to the marketplace.</p>
      </div>
      <div className="feature-card">
        <span role="img" aria-label="Buy/Sell">💱</span>
        <h3>Buy/Sell Data</h3>
        <p>Trade IoT data with buyers and sellers seamlessly.</p>
      </div>
      <div className="feature-card">
        <span role="img" aria-label="Security">🔐</span>
        <h3>Smart Contract Security</h3>
        <p>Ensure data integrity with blockchain-based contracts.</p>
      </div>
    </section>

    {/* Footer */}
    <footer className="footer">
      <div>
        <a href="#">Documentation</a> | <a href="#">Github</a> | <a href="#">Contact</a>
      </div>
      <div style={{marginTop: "8px", fontSize: "14px", color: "#718096"}}>
        © 2025 IoT DataChain. All rights reserved.
      </div>
    </footer>
  </div>
);

export default HomePage;